/* Stelly Run : textes du jeu dans toutes les langues
   Une ligne par texte : { fr, en }. Le français est la langue de référence : un texte non traduit s’affiche en français.
   Pour ajouter une langue : la déclarer dans LANGS (nom + drapeau), puis ajouter sa colonne aux textes.
   Les {n}, {name}… sont remplacés par des valeurs au moment de l’affichage. */

const LANGS = {
  fr: { name:'Français', flag:'fr' },
  en: { name:'English',  flag:'gb' }
};

// drapeaux en pixel art (11 x 8)
const LANG_FLAGS = {
  fr: ['ooooooooooo','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','ooooooooooo'],
  gb: ['ooooooooooo','owbbbrbbbwo','obwbbrbbwbo','orrrrrrrrro','orrrrrrrrro','obwbbrbbwbo','owbbbrbbbwo','ooooooooooo']
};
const LANG_FLAG_COLORS = { o:'#2E0E30', b:'#2A4FA8', w:'#FFFFFF', r:'#E0413A' };

const TEXTS = {
  // ----- interface -----
  "ui.rotate1": { fr:"Tourne ton téléphone", en:"Turn your phone" },
  "ui.rotate2": { fr:"pour jouer à Stelly Run", en:"to play Stelly Run" },
  "ui.record": { fr:"Record", en:"Best" },
  "ui.newRecord": { fr:"Nouveau record !", en:"New best!" },
  "ui.superJump": { fr:"Super saut", en:"Super jump" },
  "ui.invincible": { fr:"Invincible", en:"Invincible" },
  "ui.points": { fr:"Points", en:"Points" },
  "ui.toJump": { fr:"À sauter", en:"Jump over" },
  "ui.presents": { fr:"Lutèce Games presents", en:"Lutèce Games presents" },
  "ui.start": { fr:"Start", en:"Start" },
  "ui.install": { fr:"Installer l’appli", en:"Install the app" },
  "ui.iosInstall": { fr:"Partager puis « Sur l’écran d’accueil »", en:"Tap Share, then “Add to Home Screen”" },
  "ui.hit": { fr:"Plot touché !", en:"Hit a cone!" },
  "ui.send": { fr:"Envoyer", en:"Send" },
  "ui.home": { fr:"Accueil", en:"Home" },
  "ui.again": { fr:"Rejouer", en:"Play again" },
  "ui.orSpace": { fr:"ou appuie sur espace", en:"or press space" },
  "ui.pause": { fr:"Pause", en:"Pause" },
  "ui.resume": { fr:"Reprendre", en:"Resume" },
  "ui.pauseBtn": { fr:"Mettre en pause", en:"Pause the game" },
  "ui.sound": { fr:"Son", en:"Sound" },
  "ui.muted": { fr:"Muet", en:"Muted" },
  "ui.muteAria": { fr:"Couper le son", en:"Mute" },
  "ui.soundMenu": { fr:"Réglages du son", en:"Sound settings" },
  "ui.music": { fr:"Musique", en:"Music" },
  "ui.sfx": { fr:"Effets", en:"Effects" },
  "ui.language": { fr:"Langue", en:"Language" },
  "ui.close": { fr:"Fermer", en:"Close" },
  "ui.discsCaught": { fr:"Frisbees attrapés", en:"Frisbees caught" },
  "ui.prevPage": { fr:"Page précédente", en:"Previous page" },
  "ui.nextPage": { fr:"Page suivante", en:"Next page" },
  "toast.superJump": { fr:"Super saut !", en:"Super jump!" },
  "toast.invincible": { fr:"Invincible !", en:"Invincible!" },
  "toast.combo": { fr:"Combo !", en:"Combo!" },
  "toast.superCombo": { fr:"Super Combo !", en:"Super Combo!" },
  "toast.megaCombo": { fr:"Méga Combo !", en:"Mega Combo!" },
  "toast.gigaCombo": { fr:"Giga Combo !", en:"Giga Combo!" },
  "toast.rainbow": { fr:"Frisbee arc-en-ciel !", en:"Rainbow frisbee!" },
  "tr.title": { fr:"Trophées", en:"Trophies" },
  "tr.locked": { fr:"Pas encore débloqué", en:"Not unlocked yet" },
  "tr.lockedAria": { fr:"{name} (verrouillé)", en:"{name} (locked)" },
  "shop.title": { fr:"Boutique", en:"Shop" },
  "shop.hats": { fr:"Chapeaux", en:"Hats" },
  "shop.glasses": { fr:"Lunettes", en:"Glasses" },
  "shop.suits": { fr:"Costumes", en:"Suits" },
  "shop.shoes": { fr:"Chaussures", en:"Shoes" },
  "shop.buy": { fr:"Acheter", en:"Buy" },
  "shop.soon": { fr:"Bientôt de nouveaux articles !", en:"New items coming soon!" },
  "shop.missing": { fr:"Il te manque {n} frisbees", en:"You need {n} more frisbees" },
  "shop.price": { fr:"{n} frisbees", en:"{n} frisbees" },
  "shop.worn": { fr:"porté", en:"worn" },
  "shop.owned": { fr:"possédé", en:"owned" },
  "lb.title": { fr:"Classement", en:"Leaderboard" },
  "lb.entry": { fr:"Record perso ! Ton nom pour le classement :", en:"Personal best! Your name for the leaderboard:" },
  "lb.prevLetter": { fr:"Lettre précédente", en:"Previous letter" },
  "lb.nextLetter": { fr:"Lettre suivante", en:"Next letter" },
  "lb.loading": { fr:"Chargement…", en:"Loading…" },
  "lb.unavailable": { fr:"Classement indisponible pour le moment", en:"Leaderboard unavailable right now" },
  "lb.empty": { fr:"Sois le premier à entrer au classement !", en:"Be the first on the leaderboard!" },
  "lb.player": { fr:"{n} joueur", en:"{n} player" },
  "lb.players": { fr:"{n} joueurs", en:"{n} players" },
  "lb.sending": { fr:"Envoi…", en:"Sending…" },
  "lb.rank": { fr:"Classement mondial : n° {n}", en:"World rank: #{n}" },
  "lb.sent": { fr:"Score envoyé !", en:"Score sent!" },
  "lb.offline": { fr:"Envoi à la prochaine connexion", en:"Will be sent when you’re back online" },
  // ----- causes de mort -----
  "death.hole": { fr:"Tombée dans le trou !", en:"Fell in the hole!" },
  "death.slip": { fr:"Glissade dans la flaque !", en:"Slipped in the puddle!" },
  "death.ski": { fr:"Emmêlée dans les skis !", en:"Tangled in the skis!" },
  "death.crab": { fr:"Pincée par un crabe !", en:"Pinched by a crab!" },
  "death.mole": { fr:"Mordue par une taupe !", en:"Bitten by a mole!" },
  "death.marmot": { fr:"Mordue par une marmotte !", en:"Bitten by a marmot!" },
  "death.pigeon": { fr:"Percutée par un pigeon !", en:"Hit by a pigeon!" },
  "death.sewer": { fr:"Tombée dans une bouche d’égout !", en:"Fell down a manhole!" },
  "death.owl": { fr:"Percutée par une chouette !", en:"Hit by an owl!" },
  "death.crow": { fr:"Percutée par un corbeau !", en:"Hit by a crow!" },
  "death.stump": { fr:"Trébuchée sur du bois coupé !", en:"Tripped over a log!" },
  "death.bale": { fr:"Percutée par une botte de paille !", en:"Crashed into a hay bale!" },
  "death.gull": { fr:"Percutée par une mouette !", en:"Hit by a seagull!" },
  "death.shuttle": { fr:"Percutée par un volant !", en:"Hit by a shuttlecock!" },
  "death.eagle": { fr:"Percutée par un aigle !", en:"Hit by an eagle!" },
  // ----- trophées : nom (.n) et descriptif (.d) -----
  "tr.crampons.n": { fr:"Chausser les crampons", en:"Lace Up" },
  "tr.crampons.d": { fr:"Jouer une première partie", en:"Play your first game" },
  "tr.pasdebol.n": { fr:"Pas de bol", en:"Tough Luck" },
  "tr.pasdebol.d": { fr:"Perdre dans les 5 premières secondes", en:"Lose within the first 5 seconds" },
  "tr.taupe.n": { fr:"Taupe niveau", en:"Holy Moley" },
  "tr.taupe.d": { fr:"Tomber dans un trou de taupe", en:"Fall into a mole hole" },
  "tr.amateur.n": { fr:"Amateur", en:"Rookie" },
  "tr.amateur.d": { fr:"Jouer 5 parties", en:"Play 5 games" },
  "tr.combo5.n": { fr:"Combo", en:"Combo" },
  "tr.combo5.d": { fr:"Attraper 5 disques d’affilée", en:"Catch 5 discs in a row" },
  "tr.soldes.n": { fr:"C’est les soldes !", en:"Sale Season!" },
  "tr.soldes.d": { fr:"Acheter 1 accessoire dans la boutique", en:"Buy 1 item in the shop" },
  "tr.vitrine.n": { fr:"Lèche-vitrine", en:"Window Shopper" },
  "tr.vitrine.d": { fr:"Essayer 10 articles sans les acheter", en:"Try on 10 items without buying them" },
  "tr.gym.n": { fr:"Lippman", en:"Lippman" },
  "tr.gym.d": { fr:"Atteindre le gymnase", en:"Reach the gym" },
  "tr.beach.n": { fr:"It’s Britney Beach", en:"It’s Britney Beach" },
  "tr.beach.d": { fr:"Atteindre la plage", en:"Reach the beach" },
  "tr.city.n": { fr:"Catch in the city", en:"Catch in the City" },
  "tr.city.d": { fr:"Atteindre la ville", en:"Reach the city" },
  "tr.fields.n": { fr:"L’étoile est dans le pré", en:"Farmer Wants a Star" },
  "tr.fields.d": { fr:"Atteindre la campagne", en:"Reach the countryside" },
  "tr.forest.n": { fr:"Promenons-nous dans les bois", en:"Into the Woods" },
  "tr.forest.d": { fr:"Atteindre la forêt", en:"Reach the forest" },
  "tr.peuf.n": { fr:"Catch la Peuf", en:"Powder Day" },
  "tr.peuf.d": { fr:"Atteindre la montagne", en:"Reach the mountains" },
  "tr.junior.n": { fr:"Junior", en:"Junior" },
  "tr.junior.d": { fr:"Jouer 10 parties", en:"Play 10 games" },
  "tr.force.n": { fr:"Tour de force", en:"Tour de Force" },
  "tr.force.d": { fr:"Franchir un obstacle à 3 niveaux", en:"Clear a 3-level obstacle" },
  "tr.crabe.n": { fr:"J’en pince pour toi", en:"Pinch Me" },
  "tr.crabe.d": { fr:"Se faire pincer par un crabe", en:"Get pinched by a crab" },
  "tr.marmotte.n": { fr:"Ça va la marmotte ?", en:"Groundhog Day" },
  "tr.marmotte.d": { fr:"Se faire mordre par une marmotte", en:"Get bitten by a marmot" },
  "tr.combo10.n": { fr:"Super Combo", en:"Super Combo" },
  "tr.combo10.d": { fr:"Attraper 10 disques d’affilée", en:"Catch 10 discs in a row" },
  "tr.plumes.n": { fr:"Voler dans les plumes", en:"Feather Duster" },
  "tr.plumes.d": { fr:"Assommer 5 oiseaux en 1 partie", en:"Knock out 5 birds in 1 game" },
  "tr.mains.n": { fr:"Turn Over", en:"Turnover" },
  "tr.mains.d": { fr:"Laisser filer 25 frisbees en une partie", en:"Let 25 frisbees go by in one game" },
  "tr.requin.n": { fr:"Les dents de la mer", en:"Jaws" },
  "tr.requin.d": { fr:"Voir le requin sauter 10 fois", en:"See the shark jump 10 times" },
  "tr.deer.n": { fr:"Oh my deer", en:"Oh My Deer" },
  "tr.deer.d": { fr:"Croiser la biche et le cerf", en:"Spot both the doe and the stag" },
  "tr.globe.n": { fr:"Globe Trotter", en:"Globetrotter" },
  "tr.globe.d": { fr:"Avoir vu tous les terrains", en:"See every terrain" },
  "tr.angry.n": { fr:"Angry Birds", en:"Angry Birds" },
  "tr.angry.d": { fr:"Assommer toutes les espèces d’oiseaux", en:"Knock out every bird species" },
  "tr.bronze.n": { fr:"Handler de bronze", en:"Bronze Handler" },
  "tr.bronze.d": { fr:"1 000 frisbees catchés", en:"Catch 1,000 frisbees" },
  "tr.senior.n": { fr:"Sénior", en:"Senior" },
  "tr.senior.d": { fr:"Jouer 50 parties", en:"Play 50 games" },
  "tr.heros.n": { fr:"Super héros", en:"Superhero" },
  "tr.heros.d": { fr:"Avoir les deux pouvoirs en même temps", en:"Have both powers at the same time" },
  "tr.voltige.n": { fr:"Haute voltige", en:"High Flyer" },
  "tr.voltige.d": { fr:"Assommer un oiseau en position haute", en:"Knock out a bird flying high" },
  "tr.fashion.n": { fr:"Fashion victim", en:"Fashion Victim" },
  "tr.fashion.d": { fr:"Porter 4 accessoires en même temps", en:"Wear 4 accessories at once" },
  "tr.cendrillon.n": { fr:"Cendrillon", en:"Cinderella" },
  "tr.cendrillon.d": { fr:"Faire 3 000 points en talons", en:"Score 3,000 points in heels" },
  "tr.tetedure.n": { fr:"Tête dure", en:"Hard-Headed" },
  "tr.tetedure.d": { fr:"Assommer 10 oiseaux en portant le casque", en:"Knock out 10 birds while wearing the helmet" },
  "tr.combo50.n": { fr:"Méga Combo", en:"Mega Combo" },
  "tr.combo50.d": { fr:"Attraper 50 disques d’affilée", en:"Catch 50 discs in a row" },
  "tr.master.n": { fr:"Master", en:"Master" },
  "tr.master.d": { fr:"Jouer 100 parties", en:"Play 100 games" },
  "tr.huck.n": { fr:"Huck", en:"Huck" },
  "tr.huck.d": { fr:"Attraper 150 disques en une partie", en:"Catch 150 discs in one game" },
  "tr.elfe.n": { fr:"Un elfe libre", en:"A Free Elf" },
  "tr.elfe.d": { fr:"Attraper 3 chaussettes en 1 partie", en:"Catch 3 socks in 1 game" },
  "tr.bulldozer.n": { fr:"Bulldozer", en:"Bulldozer" },
  "tr.bulldozer.d": { fr:"Renverser 30 obstacles en 1 partie", en:"Knock over 30 obstacles in 1 game" },
  "tr.hydrate.n": { fr:"Bien hydraté", en:"Well Hydrated" },
  "tr.hydrate.d": { fr:"Boire 3 gourdes en 1 partie", en:"Drink 3 water bottles in 1 game" },
  "tr.argent.n": { fr:"Handler d’argent", en:"Silver Handler" },
  "tr.argent.d": { fr:"5 000 frisbees catchés", en:"Catch 5,000 frisbees" },
  "tr.picsou.n": { fr:"Picsou", en:"Scrooge" },
  "tr.picsou.d": { fr:"Avoir 5 000 disques de côté", en:"Save up 5,000 discs" },
  "tr.chapelier.n": { fr:"Chapelier fou", en:"Mad Hatter" },
  "tr.chapelier.d": { fr:"Posséder tous les chapeaux", en:"Own every hat" },
  "tr.gmaster.n": { fr:"Grand Master", en:"Grand Master" },
  "tr.gmaster.d": { fr:"Jouer 250 parties", en:"Play 250 games" },
  "tr.combo100.n": { fr:"Giga Combo", en:"Giga Combo" },
  "tr.combo100.d": { fr:"Attraper 100 disques d’affilée", en:"Catch 100 discs in a row" },
  "tr.or.n": { fr:"Handler d’or", en:"Gold Handler" },
  "tr.or.d": { fr:"10 000 frisbees catchés", en:"Catch 10,000 frisbees" },
  "tr.prada.n": { fr:"Stelly s’habille en Prada", en:"Stelly Wears Prada" },
  "tr.prada.d": { fr:"Dépenser 10 000 disques dans la boutique", en:"Spend 10,000 discs in the shop" },
  "tr.dressing.n": { fr:"Vide-Dressing", en:"Full Closet" },
  "tr.dressing.d": { fr:"Posséder tous les articles de la boutique", en:"Own every item in the shop" },
  "tr.intouchable.n": { fr:"Intouchable", en:"Untouchable" },
  "tr.intouchable.d": { fr:"Faire 10 000 points sans utiliser l’invincibilité", en:"Score 10,000 points without using invincibility" },
  "tr.cascadeuse.n": { fr:"Cascadeuse", en:"Stuntwoman" },
  "tr.cascadeuse.d": { fr:"Mourir de toutes les façons possibles", en:"Die in every possible way" },
  "tr.legende.n": { fr:"Légende", en:"Legend" },
  "tr.legende.d": { fr:"Jouer 500 parties", en:"Play 500 games" },
  "tr.accro.n": { fr:"Accro aux disques", en:"Disc Addict" },
  "tr.accro.d": { fr:"Jouer 1 000 parties", en:"Play 1,000 games" },
  "tr.rainbow.n": { fr:"Over the Rainbow", en:"Over the Rainbow" },
  "tr.rainbow.d": { fr:"Attraper le frisbee arc-en-ciel", en:"Catch the rainbow frisbee" },
  "tr.greatest.n": { fr:"Greatest", en:"Greatest" },
  "tr.greatest.d": { fr:"Débloquer tous les autres trophées", en:"Unlock all the other trophies" },
  "tr.parzival.n": { fr:"Parzival", en:"Parzival" },
  "tr.parzival.d": { fr:"1er au classement mondial au moins une fois", en:"Reach #1 in the world ranking at least once" },
  // ----- boutique : noms des articles -----
  "item.hat-casquette_bleue": { fr:"Casquette bleue", en:"Blue Cap" },
  "item.hat-trucker_cap_red": { fr:"Casquette trucker", en:"Trucker Cap" },
  "item.hat-bonnet": { fr:"Bonnet", en:"Beanie" },
  "item.hat-onepiece": { fr:"Chapeau de paille", en:"Straw Hat" },
  "item.hat-casque": { fr:"Casque", en:"Helmet" },
  "item.hat-sorcier": { fr:"Chapeau de sorcier", en:"Wizard Hat" },
  "item.hat-bandeau": { fr:"Bandeau", en:"Headband" },
  "item.shirt-collector": { fr:"Costume collector", en:"Collector Suit" },
  "item.shoes-basket2": { fr:"Baskets rouges", en:"Red Sneakers" },
  "item.shoes-heels": { fr:"Talons", en:"Heels" },
  "item.glasses-sun1": { fr:"Lunettes de soleil", en:"Sunglasses" },
  "item.glasses-droite": { fr:"Lunettes noires", en:"Black Shades" },
  "item.glasses-coeur": { fr:"Lunettes cœur", en:"Heart Glasses" },
  "item.glasses-stars": { fr:"Lunettes étoiles", en:"Star Glasses" },
  "item.glasses-rainbow": { fr:"Lunettes arc-en-ciel", en:"Rainbow Glasses" },
  "item.shirt-bleu": { fr:"Costume bleu", en:"Blue Suit" },
  "item.shirt-vert": { fr:"Costume vert", en:"Green Suit" },
  "item.shirt-violet": { fr:"Costume violet", en:"Purple Suit" },
  "item.shoes-tong": { fr:"Tongs", en:"Flip-Flops" },
  "item.shoes-basket_bleu": { fr:"Baskets bleues", en:"Blue Sneakers" },
  "item.shoes-basket_rouges_montante": { fr:"Montantes rouges", en:"Red High-Tops" }
};
