/* Stelly Run : textes du jeu dans toutes les langues
   Une ligne par texte : { fr, en }. Le français est la langue de référence : un texte non traduit s’affiche en français.
   Pour ajouter une langue : la déclarer dans LANGS (nom + drapeau), puis ajouter sa colonne aux textes.
   Les {n}, {name}… sont remplacés par des valeurs au moment de l’affichage. */

const LANGS = {
  fr: { name:'Français', flag:'fr' },
  en: { name:'English',  flag:'gb' },
  es: { name:'Español',  flag:'es' }
};

// drapeaux en pixel art (11 x 8)
const LANG_FLAGS = {
  fr: ['ooooooooooo','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','obbbwwwrrro','ooooooooooo'],
  gb: ['ooooooooooo','owbbbrbbbwo','obwbbrbbwbo','orrrrrrrrro','orrrrrrrrro','obwbbrbbwbo','owbbbrbbbwo','ooooooooooo'],
  es: ['ooooooooooo','orrrrrrrrro','oyyyyyyyyyo','oyyyyyyyyyo','oyyyyyyyyyo','oyyyyyyyyyo','orrrrrrrrro','ooooooooooo']
};
const LANG_FLAG_COLORS = { o:'#2E0E30', b:'#2A4FA8', w:'#FFFFFF', r:'#E0413A', y:'#FFCF00' };

const TEXTS = {
  // ----- interface -----
  "ui.rotate1": { fr:"Tourne ton téléphone", en:"Turn your phone", es:"Gira tu teléfono" },
  "ui.rotate2": { fr:"pour jouer à Stelly Run", en:"to play Stelly Run", es:"para jugar a Stelly Run" },
  "ui.record": { fr:"Record", en:"Best", es:"Récord" },
  "ui.newRecord": { fr:"Nouveau record !", en:"New best!", es:"¡Nuevo récord!" },
  "ui.superJump": { fr:"Super saut", en:"Super jump", es:"Supersalto" },
  "ui.invincible": { fr:"Invincible", en:"Invincible", es:"Invencible" },
  "ui.points": { fr:"Points", en:"Points", es:"Puntos" },
  "ui.toJump": { fr:"À sauter", en:"Jump over", es:"Saltar" },
  "ui.presents": { fr:"Lutèce Games presents", en:"Lutèce Games presents", es:"Lutèce Games presenta" },
  "ui.start": { fr:"Start", en:"Start", es:"Jugar" },
  "ui.install": { fr:"Installer l’appli", en:"Install the app", es:"Instalar la app" },
  "ui.iosInstall": { fr:"Partager puis « Sur l’écran d’accueil »", en:"Tap Share, then “Add to Home Screen”", es:"Pulsa Compartir y luego «Añadir a pantalla de inicio»" },
  "ui.hit": { fr:"Plot touché !", en:"Hit a cone!", es:"¡Cono golpeado!" },
  "ui.send": { fr:"Envoyer", en:"Send", es:"Enviar" },
  "ui.home": { fr:"Accueil", en:"Home", es:"Inicio" },
  "ui.again": { fr:"Rejouer", en:"Play again", es:"Otra vez" },
  "ui.orSpace": { fr:"ou appuie sur espace", en:"or press space", es:"o pulsa espacio" },
  "ui.pause": { fr:"Pause", en:"Pause", es:"Pausa" },
  "ui.resume": { fr:"Reprendre", en:"Resume", es:"Seguir" },
  "ui.pauseBtn": { fr:"Mettre en pause", en:"Pause the game", es:"Pausar el juego" },
  "ui.sound": { fr:"Son", en:"Sound", es:"Sonido" },
  "ui.muted": { fr:"Muet", en:"Muted", es:"Silencio" },
  "ui.muteAria": { fr:"Couper le son", en:"Mute", es:"Silenciar" },
  "ui.soundMenu": { fr:"Réglages du son", en:"Sound settings", es:"Ajustes de sonido" },
  "ui.music": { fr:"Musique", en:"Music", es:"Música" },
  "ui.sfx": { fr:"Effets", en:"Effects", es:"Efectos" },
  "ui.language": { fr:"Langue", en:"Language", es:"Idioma" },
  "ui.close": { fr:"Fermer", en:"Close", es:"Cerrar" },
  "ui.discsCaught": { fr:"Frisbees attrapés", en:"Frisbees caught", es:"Frisbees atrapados" },
  "ui.prevPage": { fr:"Page précédente", en:"Previous page", es:"Página anterior" },
  "ui.nextPage": { fr:"Page suivante", en:"Next page", es:"Página siguiente" },
  "toast.superJump": { fr:"Super saut !", en:"Super jump!", es:"¡Supersalto!" },
  "toast.invincible": { fr:"Invincible !", en:"Invincible!", es:"¡Invencible!" },
  "toast.combo": { fr:"Combo !", en:"Combo!", es:"¡Combo!" },
  "toast.superCombo": { fr:"Super Combo !", en:"Super Combo!", es:"¡Super Combo!" },
  "toast.megaCombo": { fr:"Méga Combo !", en:"Mega Combo!", es:"¡Mega Combo!" },
  "toast.gigaCombo": { fr:"Giga Combo !", en:"Giga Combo!", es:"¡Giga Combo!" },
  "toast.rainbow": { fr:"Frisbee arc-en-ciel !", en:"Rainbow frisbee!", es:"¡Frisbee arcoíris!" },
  "tr.title": { fr:"Trophées", en:"Trophies", es:"Trofeos" },
  "tr.locked": { fr:"Pas encore débloqué", en:"Not unlocked yet", es:"Aún no desbloqueado" },
  "tr.lockedAria": { fr:"{name} (verrouillé)", en:"{name} (locked)", es:"{name} (bloqueado)" },
  "shop.title": { fr:"Boutique", en:"Shop", es:"Tienda" },
  "shop.hats": { fr:"Chapeaux", en:"Hats", es:"Sombreros" },
  "shop.glasses": { fr:"Lunettes", en:"Glasses", es:"Gafas" },
  "shop.suits": { fr:"Costumes", en:"Suits", es:"Trajes" },
  "shop.shoes": { fr:"Chaussures", en:"Shoes", es:"Zapatos" },
  "shop.buy": { fr:"Acheter", en:"Buy", es:"Comprar" },
  "shop.soon": { fr:"Bientôt de nouveaux articles !", en:"New items coming soon!", es:"¡Pronto habrá nuevos artículos!" },
  "shop.missing": { fr:"Il te manque {n} frisbees", en:"You need {n} more frisbees", es:"Te faltan {n} frisbees" },
  "shop.price": { fr:"{n} frisbees", en:"{n} frisbees", es:"{n} frisbees" },
  "shop.worn": { fr:"porté", en:"worn", es:"puesto" },
  "shop.owned": { fr:"possédé", en:"owned", es:"comprado" },
  "lb.title": { fr:"Classement", en:"Leaderboard", es:"Clasificación" },
  "lb.entry": { fr:"Record perso ! Ton nom pour le classement :", en:"Personal best! Your name for the leaderboard:", es:"¡Récord personal! Tu nombre para la clasificación:" },
  "lb.prevLetter": { fr:"Lettre précédente", en:"Previous letter", es:"Letra anterior" },
  "lb.nextLetter": { fr:"Lettre suivante", en:"Next letter", es:"Letra siguiente" },
  "lb.loading": { fr:"Chargement…", en:"Loading…", es:"Cargando…" },
  "lb.unavailable": { fr:"Classement indisponible pour le moment", en:"Leaderboard unavailable right now", es:"Clasificación no disponible por ahora" },
  "lb.empty": { fr:"Sois le premier à entrer au classement !", en:"Be the first on the leaderboard!", es:"¡Sé el primero en la clasificación!" },
  "lb.player": { fr:"{n} joueur", en:"{n} player", es:"{n} jugador" },
  "lb.players": { fr:"{n} joueurs", en:"{n} players", es:"{n} jugadores" },
  "lb.sending": { fr:"Envoi…", en:"Sending…", es:"Enviando…" },
  "lb.rank": { fr:"Classement mondial : n° {n}", en:"World rank: #{n}", es:"Ranking mundial: n.º {n}" },
  "lb.sent": { fr:"Score envoyé !", en:"Score sent!", es:"¡Puntuación enviada!" },
  "lb.offline": { fr:"Envoi à la prochaine connexion", en:"Will be sent when you’re back online", es:"Se enviará cuando vuelvas a tener conexión" },
  // ----- écran de fin -----
  "over.gap": { fr:"À {n} pts de ton record", en:"{n} pts short of your best", es:"A {n} pts de tu récord" },
  "over.tie": { fr:"Égalité avec ton record !", en:"You tied your best!", es:"¡Igualas tu récord!" },
  "over.newBest": { fr:"Nouveau record ! +{n}", en:"New best! +{n}", es:"¡Nuevo récord! +{n}" },
  "over.coins": { fr:"frisbees gagnés", en:"frisbees earned", es:"frisbees ganados" },
  "over.streak": { fr:"meilleure série", en:"best streak", es:"mejor racha" },
  "over.trophy1": { fr:"1 trophée !", en:"1 trophy!", es:"¡1 trofeo!" },
  "over.trophies": { fr:"{n} trophées !", en:"{n} trophies!", es:"¡{n} trofeos!" },
  // ----- causes de mort -----
  "death.hole": { fr:"Tombée dans le trou !", en:"Fell in the hole!", es:"¡Caída en el agujero!" },
  "death.slip": { fr:"Glissade dans la flaque !", en:"Slipped in the puddle!", es:"¡Resbalón en el charco!" },
  "death.ski": { fr:"Emmêlée dans les skis !", en:"Tangled in the skis!", es:"¡Enredada en los esquís!" },
  "death.crab": { fr:"Pincée par un crabe !", en:"Pinched by a crab!", es:"¡Pellizcada por un cangrejo!" },
  "death.mole": { fr:"Mordue par une taupe !", en:"Bitten by a mole!", es:"¡Mordida por un topo!" },
  "death.marmot": { fr:"Mordue par une marmotte !", en:"Bitten by a marmot!", es:"¡Mordida por una marmota!" },
  "death.pigeon": { fr:"Percutée par un pigeon !", en:"Hit by a pigeon!", es:"¡Golpeada por una paloma!" },
  "death.sewer": { fr:"Tombée dans une bouche d’égout !", en:"Fell down a manhole!", es:"¡Caída en una alcantarilla!" },
  "death.owl": { fr:"Percutée par une chouette !", en:"Hit by an owl!", es:"¡Golpeada por una lechuza!" },
  "death.crow": { fr:"Percutée par un corbeau !", en:"Hit by a crow!", es:"¡Golpeada por un cuervo!" },
  "death.stump": { fr:"Trébuchée sur du bois coupé !", en:"Tripped over a log!", es:"¡Tropiezo con un tronco!" },
  "death.bale": { fr:"Percutée par une botte de paille !", en:"Crashed into a hay bale!", es:"¡Choque con una bala de paja!" },
  "death.gull": { fr:"Percutée par une mouette !", en:"Hit by a seagull!", es:"¡Golpeada por una gaviota!" },
  "death.shuttle": { fr:"Percutée par un volant !", en:"Hit by a shuttlecock!", es:"¡Golpeada por un volante!" },
  "death.eagle": { fr:"Percutée par un aigle !", en:"Hit by an eagle!", es:"¡Golpeada por un águila!" },
  // ----- trophées : nom (.n) et descriptif (.d) -----
  "tr.crampons.n": { fr:"Chausser les crampons", en:"Lace Up", es:"Atarse las botas" },
  "tr.crampons.d": { fr:"Jouer une première partie", en:"Play your first game", es:"Juega tu primera partida" },
  "tr.pasdebol.n": { fr:"Pas de bol", en:"Tough Luck", es:"Mala suerte" },
  "tr.pasdebol.d": { fr:"Perdre dans les 5 premières secondes", en:"Lose within the first 5 seconds", es:"Pierde en los 5 primeros segundos" },
  "tr.taupe.n": { fr:"Taupe niveau", en:"Holy Moley", es:"Topo de gama" },
  "tr.taupe.d": { fr:"Tomber dans un trou de taupe", en:"Fall into a mole hole", es:"Cae en un agujero de topo" },
  "tr.amateur.n": { fr:"Amateur", en:"Rookie", es:"Aficionado" },
  "tr.amateur.d": { fr:"Jouer 5 parties", en:"Play 5 games", es:"Juega 5 partidas" },
  "tr.combo5.n": { fr:"Combo", en:"Combo", es:"Combo" },
  "tr.combo5.d": { fr:"Attraper 5 disques d’affilée", en:"Catch 5 discs in a row", es:"Atrapa 5 discos seguidos" },
  "tr.soldes.n": { fr:"C’est les soldes !", en:"Sale Season!", es:"¡Rebajas!" },
  "tr.soldes.d": { fr:"Acheter 1 accessoire dans la boutique", en:"Buy 1 item in the shop", es:"Compra 1 accesorio en la tienda" },
  "tr.vitrine.n": { fr:"Lèche-vitrine", en:"Window Shopper", es:"Mirar escaparates" },
  "tr.vitrine.d": { fr:"Essayer 10 articles sans les acheter", en:"Try on 10 items without buying them", es:"Pruébate 10 artículos sin comprarlos" },
  "tr.gym.n": { fr:"Lippman", en:"Lippman", es:"Lippman" },
  "tr.gym.d": { fr:"Atteindre le gymnase", en:"Reach the gym", es:"Llega al gimnasio" },
  "tr.beach.n": { fr:"It’s Britney Beach", en:"It’s Britney Beach", es:"It’s Britney Beach" },
  "tr.beach.d": { fr:"Atteindre la plage", en:"Reach the beach", es:"Llega a la playa" },
  "tr.city.n": { fr:"Catch in the city", en:"Catch in the City", es:"Catch in the City" },
  "tr.city.d": { fr:"Atteindre la ville", en:"Reach the city", es:"Llega a la ciudad" },
  "tr.fields.n": { fr:"L’étoile est dans le pré", en:"Farmer Wants a Star", es:"Granjero busca estrella" },
  "tr.fields.d": { fr:"Atteindre la campagne", en:"Reach the countryside", es:"Llega al campo" },
  "tr.forest.n": { fr:"Promenons-nous dans les bois", en:"Into the Woods", es:"Jugaremos en el bosque" },
  "tr.forest.d": { fr:"Atteindre la forêt", en:"Reach the forest", es:"Llega al bosque" },
  "tr.peuf.n": { fr:"Catch la Peuf", en:"Powder Day", es:"¡Nieve polvo!" },
  "tr.peuf.d": { fr:"Atteindre la montagne", en:"Reach the mountains", es:"Llega a la montaña" },
  "tr.junior.n": { fr:"Junior", en:"Junior", es:"Junior" },
  "tr.junior.d": { fr:"Jouer 10 parties", en:"Play 10 games", es:"Juega 10 partidas" },
  "tr.force.n": { fr:"Tour de force", en:"Tour de Force", es:"Tour de force" },
  "tr.force.d": { fr:"Franchir un obstacle à 3 niveaux", en:"Clear a 3-level obstacle", es:"Supera un obstáculo de 3 niveles" },
  "tr.crabe.n": { fr:"J’en pince pour toi", en:"Pinch Me", es:"Me tienes pillada" },
  "tr.crabe.d": { fr:"Se faire pincer par un crabe", en:"Get pinched by a crab", es:"Que te pellizque un cangrejo" },
  "tr.marmotte.n": { fr:"Ça va la marmotte ?", en:"Groundhog Day", es:"El día de la marmota" },
  "tr.marmotte.d": { fr:"Se faire mordre par une marmotte", en:"Get bitten by a marmot", es:"Que te muerda una marmota" },
  "tr.combo10.n": { fr:"Super Combo", en:"Super Combo", es:"Super Combo" },
  "tr.combo10.d": { fr:"Attraper 10 disques d’affilée", en:"Catch 10 discs in a row", es:"Atrapa 10 discos seguidos" },
  "tr.plumes.n": { fr:"Voler dans les plumes", en:"Feather Duster", es:"Plumas al viento" },
  "tr.plumes.d": { fr:"Assommer 5 oiseaux en 1 partie", en:"Knock out 5 birds in 1 game", es:"Noquea 5 pájaros en 1 partida" },
  "tr.mains.n": { fr:"Turn Over", en:"Turnover", es:"Turnover" },
  "tr.mains.d": { fr:"Laisser filer 25 frisbees en une partie", en:"Let 25 frisbees go by in one game", es:"Deja pasar 25 frisbees en una partida" },
  "tr.requin.n": { fr:"Les dents de la mer", en:"Jaws", es:"Tiburón" },
  "tr.requin.d": { fr:"Voir le requin sauter 10 fois", en:"See the shark jump 10 times", es:"Ve al tiburón saltar 10 veces" },
  "tr.deer.n": { fr:"Oh my deer", en:"Oh My Deer", es:"Oh my deer" },
  "tr.deer.d": { fr:"Croiser la biche et le cerf", en:"Spot both the doe and the stag", es:"Cruza a la cierva y al ciervo" },
  "tr.globe.n": { fr:"Globe Trotter", en:"Globetrotter", es:"Trotamundos" },
  "tr.globe.d": { fr:"Avoir vu tous les terrains", en:"See every terrain", es:"Ve todos los terrenos" },
  "tr.angry.n": { fr:"Angry Birds", en:"Angry Birds", es:"Angry Birds" },
  "tr.angry.d": { fr:"Assommer toutes les espèces d’oiseaux", en:"Knock out every bird species", es:"Noquea todas las especies de pájaros" },
  "tr.bronze.n": { fr:"Handler de bronze", en:"Bronze Handler", es:"Handler de bronce" },
  "tr.bronze.d": { fr:"1 000 frisbees catchés", en:"Catch 1,000 frisbees", es:"Atrapa 1.000 frisbees" },
  "tr.senior.n": { fr:"Sénior", en:"Senior", es:"Sénior" },
  "tr.senior.d": { fr:"Jouer 50 parties", en:"Play 50 games", es:"Juega 50 partidas" },
  "tr.heros.n": { fr:"Super héros", en:"Superhero", es:"Superhéroe" },
  "tr.heros.d": { fr:"Avoir les deux pouvoirs en même temps", en:"Have both powers at the same time", es:"Ten los dos poderes a la vez" },
  "tr.voltige.n": { fr:"Haute voltige", en:"High Flyer", es:"Altos vuelos" },
  "tr.voltige.d": { fr:"Assommer un oiseau en position haute", en:"Knock out a bird flying high", es:"Noquea a un pájaro en lo alto" },
  "tr.fashion.n": { fr:"Fashion victim", en:"Fashion Victim", es:"Fashion victim" },
  "tr.fashion.d": { fr:"Porter 4 accessoires en même temps", en:"Wear 4 accessories at once", es:"Lleva 4 accesorios a la vez" },
  "tr.cendrillon.n": { fr:"Cendrillon", en:"Cinderella", es:"Cenicienta" },
  "tr.cendrillon.d": { fr:"Faire 3 000 points en talons", en:"Score 3,000 points in heels", es:"Haz 3.000 puntos con tacones" },
  "tr.tetedure.n": { fr:"Tête dure", en:"Hard-Headed", es:"Cabeza dura" },
  "tr.tetedure.d": { fr:"Assommer 10 oiseaux en portant le casque", en:"Knock out 10 birds while wearing the helmet", es:"Noquea 10 pájaros llevando el casco" },
  "tr.combo50.n": { fr:"Méga Combo", en:"Mega Combo", es:"Mega Combo" },
  "tr.combo50.d": { fr:"Attraper 50 disques d’affilée", en:"Catch 50 discs in a row", es:"Atrapa 50 discos seguidos" },
  "tr.master.n": { fr:"Master", en:"Master", es:"Master" },
  "tr.master.d": { fr:"Jouer 100 parties", en:"Play 100 games", es:"Juega 100 partidas" },
  "tr.huck.n": { fr:"Huck", en:"Huck", es:"Huck" },
  "tr.huck.d": { fr:"Attraper 150 disques en une partie", en:"Catch 150 discs in one game", es:"Atrapa 150 discos en una partida" },
  "tr.elfe.n": { fr:"Un elfe libre", en:"A Free Elf", es:"Un elfo libre" },
  "tr.elfe.d": { fr:"Attraper 3 chaussettes en 1 partie", en:"Catch 3 socks in 1 game", es:"Atrapa 3 calcetines en 1 partida" },
  "tr.bulldozer.n": { fr:"Bulldozer", en:"Bulldozer", es:"Bulldozer" },
  "tr.bulldozer.d": { fr:"Renverser 30 obstacles en 1 partie", en:"Knock over 30 obstacles in 1 game", es:"Derriba 30 obstáculos en 1 partida" },
  "tr.hydrate.n": { fr:"Bien hydraté", en:"Well Hydrated", es:"Bien hidratada" },
  "tr.hydrate.d": { fr:"Boire 3 gourdes en 1 partie", en:"Drink 3 water bottles in 1 game", es:"Bebe 3 cantimploras en 1 partida" },
  "tr.argent.n": { fr:"Handler d’argent", en:"Silver Handler", es:"Handler de plata" },
  "tr.argent.d": { fr:"5 000 frisbees catchés", en:"Catch 5,000 frisbees", es:"Atrapa 5.000 frisbees" },
  "tr.picsou.n": { fr:"Picsou", en:"Scrooge", es:"Tío Gilito" },
  "tr.picsou.d": { fr:"Avoir 5 000 disques de côté", en:"Save up 5,000 discs", es:"Ahorra 5.000 discos" },
  "tr.chapelier.n": { fr:"Chapelier fou", en:"Mad Hatter", es:"Sombrerero loco" },
  "tr.chapelier.d": { fr:"Posséder tous les chapeaux", en:"Own every hat", es:"Ten todos los sombreros" },
  "tr.gmaster.n": { fr:"Grand Master", en:"Grand Master", es:"Gran Maestro" },
  "tr.gmaster.d": { fr:"Jouer 250 parties", en:"Play 250 games", es:"Juega 250 partidas" },
  "tr.combo100.n": { fr:"Giga Combo", en:"Giga Combo", es:"Giga Combo" },
  "tr.combo100.d": { fr:"Attraper 100 disques d’affilée", en:"Catch 100 discs in a row", es:"Atrapa 100 discos seguidos" },
  "tr.or.n": { fr:"Handler d’or", en:"Gold Handler", es:"Handler de oro" },
  "tr.or.d": { fr:"10 000 frisbees catchés", en:"Catch 10,000 frisbees", es:"Atrapa 10.000 frisbees" },
  "tr.prada.n": { fr:"Stelly s’habille en Prada", en:"Stelly Wears Prada", es:"Stelly viste de Prada" },
  "tr.prada.d": { fr:"Dépenser 10 000 disques dans la boutique", en:"Spend 10,000 discs in the shop", es:"Gasta 10.000 discos en la tienda" },
  "tr.dressing.n": { fr:"Vide-Dressing", en:"Full Closet", es:"Armario lleno" },
  "tr.dressing.d": { fr:"Posséder tous les articles de la boutique", en:"Own every item in the shop", es:"Ten todos los artículos de la tienda" },
  "tr.intouchable.n": { fr:"Intouchable", en:"Untouchable", es:"Intocable" },
  "tr.intouchable.d": { fr:"Faire 10 000 points sans utiliser l’invincibilité", en:"Score 10,000 points without using invincibility", es:"Haz 10.000 puntos sin usar la invencibilidad" },
  "tr.cascadeuse.n": { fr:"Cascadeuse", en:"Stuntwoman", es:"Doble de riesgo" },
  "tr.cascadeuse.d": { fr:"Mourir de toutes les façons possibles", en:"Die in every possible way", es:"Muere de todas las formas posibles" },
  "tr.legende.n": { fr:"Légende", en:"Legend", es:"Leyenda" },
  "tr.legende.d": { fr:"Jouer 500 parties", en:"Play 500 games", es:"Juega 500 partidas" },
  "tr.accro.n": { fr:"Accro aux disques", en:"Disc Addict", es:"Adicto a los discos" },
  "tr.accro.d": { fr:"Jouer 1 000 parties", en:"Play 1,000 games", es:"Juega 1.000 partidas" },
  "tr.rainbow.n": { fr:"Over the Rainbow", en:"Over the Rainbow", es:"Over the Rainbow" },
  "tr.rainbow.d": { fr:"Attraper le frisbee arc-en-ciel", en:"Catch the rainbow frisbee", es:"Atrapa el frisbee arcoíris" },
  "tr.greatest.n": { fr:"Greatest", en:"Greatest", es:"Greatest" },
  "tr.greatest.d": { fr:"Débloquer tous les autres trophées", en:"Unlock all the other trophies", es:"Desbloquea todos los demás trofeos" },
  "tr.parzival.n": { fr:"Parzival", en:"Parzival", es:"Parzival" },
  "tr.parzival.d": { fr:"1er au classement mondial au moins une fois", en:"Reach #1 in the world ranking at least once", es:"Sé n.º 1 del ranking mundial al menos una vez" },
};
